version: "3.8"

services:
  
  backend:
    user: "1000:1000"
    hostname: backend
    container_name: backend
    image: made22t4/backend:1.0
    ports:
      - "8888:8888"
    expose:
      - "8888:8888"
    volumes:
      - ${PWD}/../backend:/usr/src/app
    entrypoint: uvicorn main:app --reload --host 0.0.0.0 --port 8888
    command: ""

  frontend:
    user: "1000:1000"
    hostname: frontend
    container_name: frontend
    image: made22t4/frontend:1.0
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/../frontend/site:/usr/src/app
    entrypoint: sh -c "yarn install && yarn generate && yarn start"
    environment:
      - HOST=0.0.0.0
    command: ""

  database:
    hostname: database
    container_name: database
    image: mongo:6
    expose:
      - "27017:27017"
    volumes:
      - made22t4-database:/data/db

  logs-front:
    hostname: logs-front
    container_name: logs-front
    image: made22t4/logs-front:1.0
    ports:
      - "9000:3000"

  logs-back:
    hostname: logs-back
    container_name: logs-back
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/../logs/prometheus.yml:/etc/prometheus/prometheus.yml

  qdrant:
    image: qdrant/qdrant:v0.11.5
    hostname: qdrant
    container_name: qdrant
    networks:
      - workspace
    expose:
      - 6333

volumes:
  made22t4-database:
    external: true
