version: "3.8"

services:

  database:
    hostname: database
    container_name: database
    image: mongo:6
    volumes:
      - made22t4-database:/data/db
    ports:
      - "27017:27017"
  
  logs-front:
    hostname: logs-front
    container_name: logs-front
    image: made22t4/logs:1.0
    ports:
      - "9000:3000"

  logs-back:
    hostname: logs-back
    container_name: logs-back
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - workspace
    volumes:
      - ${PWD}/../logs/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  made22t4-database:
    external: true
