name: Python package

on:
  - pull_request
  - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        mongodb-version: [6.0]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install dependencies
        run: |
          sudo apt install -y git-lfs
          pip install -r backend/requirements.txt
      - name: Install ML dependencies
        run: |
          pip install -r backend/requirements.ml.txt
          python backend/ml/lda/prepare.py
      - name: Lint with flake8
        run: |
           flake8 . --count --max-line-length=120 --show-source --statistics --ignore=F403,F405,W605,F811
      - name: Test with pytest
        run: |
          export MONGODB_URI=${{ secrets.MONGODB_URI }}
          pytest -svv